import type { Metadata } from 'next';
import { Inter, Work_Sans } from 'next/font/google';
import './globals.css';
import CursorEffect from '@/components/shared/CursorEffect';
import Navbar from '@/components/shared/navbar/Navbar';
import { SmoothScrollProvider } from '@/components/shared/SmoothScrollProvider';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

const workSans = Work_Sans({
  variable: '--font-work-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Dental Lab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${workSans.variable} antialiased`}>
        <SmoothScrollProvider>
          <CursorEffect />
          <Navbar />
          {children}
          <Toaster />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
